spring.application.name=kafka-producer
server.port=0
spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.acks=all

# spring.kafka.producer.retries=10
# spring.kafka.producer.properties.retry.backoff.ms=1000

# delivery.timeout.ms >= linger.ms + request.timeout.ms
spring.kafka.producer.properties.delivery.timeout.ms=120000 
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000